apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-azure-network
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-azure-network
    meta.crossplane.io/license: Apache-2.0

spec:
  crossplane:
    version: ">=v1.13.2-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-azure
      version: "v0.37.1"
    - provider: xpkg.upbound.io/upbound/provider-azure-network
      version: "v0.37.1"
