name: Composition Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  composition-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install up
        run: |
          curl -sL "https://cli.upbound.io" | sh
          mv up /usr/local/bin
          chmod +x /usr/local/bin/up

      - name: Build project
        run: up project build

      - name: Run composition tests
        run: up test run tests/*
