name: End to End Testing

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}

      - name: Build project
        run: up project build

      - name: Switch up context
        run: up ctx upboundcare/upbound-gcp-us-central-1/default

      - name: Run composition tests
        run: up test run tests/* --e2e
